apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: language
spec:
  template:
    metadata:
      labels:
        app: language-app
    spec:
      containers:
      - name: language
        image: mcr.microsoft.com/azure-cognitive-services/language
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 1
        env:
        - name: EULA
          value: "accept"
        - name: billing
          value: https://vishwas123.cognitiveservices.azure.com/ # {ENDPOINT_URI}
        - name: apikey
          value:  746abc5115a14acb8a94c89c1dff9569 # {API_KEY}

--- 
apiVersion: v1
kind: Service
metadata:
  name: language
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: language-app


    # kubectl apply -f language.yaml